//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.res", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about us.
        /// </summary>
        internal static string aboutUs {
            get {
                return ResourceManager.GetString("aboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string addComment {
            get {
                return ResourceManager.GetString("addComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Address.
        /// </summary>
        internal static string addNewAddress {
            get {
                return ResourceManager.GetString("addNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Address.
        /// </summary>
        internal static string addressChange {
            get {
                return ResourceManager.GetString("addressChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your Address.
        /// </summary>
        internal static string addressChoice {
            get {
                return ResourceManager.GetString("addressChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Detail.
        /// </summary>
        internal static string addressDetail {
            get {
                return ResourceManager.GetString("addressDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address .
        /// </summary>
        internal static string addressLable {
            get {
                return ResourceManager.GetString("addressLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to basket.
        /// </summary>
        internal static string addToCart {
            get {
                return ResourceManager.GetString("addToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add for compare.
        /// </summary>
        internal static string addToCompareList {
            get {
                return ResourceManager.GetString("addToCompareList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for compare.
        /// </summary>
        internal static string addToListCompare {
            get {
                return ResourceManager.GetString("addToListCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to wallet.
        /// </summary>
        internal static string addToWalet {
            get {
                return ResourceManager.GetString("addToWalet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert title to add your items.
        /// </summary>
        internal static string addToWishListName {
            get {
                return ResourceManager.GetString("addToWishListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you must agree with terms.
        /// </summary>
        internal static string agreeTerm {
            get {
                return ResourceManager.GetString("agreeTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree with terms and conditions.
        /// </summary>
        internal static string agreeWithTerms {
            get {
                return ResourceManager.GetString("agreeWithTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notify me when available.
        /// </summary>
        internal static string alertIfAvailable {
            get {
                return ResourceManager.GetString("alertIfAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all rights reserve for website .
        /// </summary>
        internal static string allRightReserved {
            get {
                return ResourceManager.GetString("allRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all rights reserve for .
        /// </summary>
        internal static string allrightReservedFor {
            get {
                return ResourceManager.GetString("allrightReservedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available in resort.
        /// </summary>
        internal static string anbarMojood {
            get {
                return ResourceManager.GetString("anbarMojood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string and1 {
            get {
                return ResourceManager.GetString("and1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to balance.
        /// </summary>
        internal static string balance {
            get {
                return ResourceManager.GetString("balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basket.
        /// </summary>
        internal static string basket {
            get {
                return ResourceManager.GetString("basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basket.
        /// </summary>
        internal static string basket1 {
            get {
                return ResourceManager.GetString("basket1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your product is added successfully.
        /// </summary>
        internal static string basketAddConfirm {
            get {
                return ResourceManager.GetString("basketAddConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item is added to basket.
        /// </summary>
        internal static string basketAddConfirm1 {
            get {
                return ResourceManager.GetString("basketAddConfirm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debt.
        /// </summary>
        internal static string bedehkari {
            get {
                return ResourceManager.GetString("bedehkari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string bestankari {
            get {
                return ResourceManager.GetString("bestankari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usefull comments.
        /// </summary>
        internal static string bestComment {
            get {
                return ResourceManager.GetString("bestComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Sellers.
        /// </summary>
        internal static string bestSeller {
            get {
                return ResourceManager.GetString("bestSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be the first one who set his comment.
        /// </summary>
        internal static string beTheFirst {
            get {
                return ResourceManager.GetString("beTheFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to performance is better in application.
        /// </summary>
        internal static string betterPerformance {
            get {
                return ResourceManager.GetString("betterPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blog.
        /// </summary>
        internal static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buyer of this Item.
        /// </summary>
        internal static string buyerOfProduct {
            get {
                return ResourceManager.GetString("buyerOfProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By.
        /// </summary>
        internal static string by {
            get {
                return ResourceManager.GetString("by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By seller at.
        /// </summary>
        internal static string bySellerInDate {
            get {
                return ResourceManager.GetString("bySellerInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call please.
        /// </summary>
        internal static string callPls {
            get {
                return ResourceManager.GetString("callPls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you cannot register your comment for this item.
        /// </summary>
        internal static string cannotComment {
            get {
                return ResourceManager.GetString("cannotComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to category.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to changes are done .
        /// </summary>
        internal static string chanagesAreDone {
            get {
                return ResourceManager.GetString("chanagesAreDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address change.
        /// </summary>
        internal static string changeAddress {
            get {
                return ResourceManager.GetString("changeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password change.
        /// </summary>
        internal static string changePass {
            get {
                return ResourceManager.GetString("changePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string changePassLable {
            get {
                return ResourceManager.GetString("changePassLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password change.
        /// </summary>
        internal static string changePassword {
            get {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit personal information.
        /// </summary>
        internal static string changePersonalData {
            get {
                return ResourceManager.GetString("changePersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        internal static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to city.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discount is applied.
        /// </summary>
        internal static string codeInserted {
            get {
                return ResourceManager.GetString("codeInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to color.
        /// </summary>
        internal static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other color.
        /// </summary>
        internal static string colorList {
            get {
                return ResourceManager.GetString("colorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your comment content.
        /// </summary>
        internal static string commentContent {
            get {
                return ResourceManager.GetString("commentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comments.
        /// </summary>
        internal static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your comment is registered successfully.
        /// </summary>
        internal static string commentSet {
            get {
                return ResourceManager.GetString("commentSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comparation list.
        /// </summary>
        internal static string compareItem {
            get {
                return ResourceManager.GetString("compareItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to compaint content.
        /// </summary>
        internal static string complainText {
            get {
                return ResourceManager.GetString("complainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register complaint.
        /// </summary>
        internal static string complaintRegistration {
            get {
                return ResourceManager.GetString("complaintRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your complaint is registered successfully.
        /// </summary>
        internal static string complaintSettled {
            get {
                return ResourceManager.GetString("complaintSettled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to complete complaint content please.
        /// </summary>
        internal static string completeComplainText {
            get {
                return ResourceManager.GetString("completeComplainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        internal static string contactUs {
            get {
                return ResourceManager.GetString("contactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert correct username.
        /// </summary>
        internal static string correctUsername {
            get {
                return ResourceManager.GetString("correctUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reform your basket.
        /// </summary>
        internal static string correctYourFactor {
            get {
                return ResourceManager.GetString("correctYourFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count.
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to created by .
        /// </summary>
        internal static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to customer services.
        /// </summary>
        internal static string customerService {
            get {
                return ResourceManager.GetString("customerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        internal static string d {
            get {
                return ResourceManager.GetString("d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inplace payment.
        /// </summary>
        internal static string darmahal {
            get {
                return ResourceManager.GetString("darmahal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivery fee.
        /// </summary>
        internal static string deliverPrice {
            get {
                return ResourceManager.GetString("deliverPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delivery time.
        /// </summary>
        internal static string deliverTime {
            get {
                return ResourceManager.GetString("deliverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order delivery time.
        /// </summary>
        internal static string deliveryDate {
            get {
                return ResourceManager.GetString("deliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details list.
        /// </summary>
        internal static string detailList {
            get {
                return ResourceManager.GetString("detailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direct download.
        /// </summary>
        internal static string directDownload {
            get {
                return ResourceManager.GetString("directDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discount.
        /// </summary>
        internal static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beware of last news and discount.
        /// </summary>
        internal static string discountAlert {
            get {
                return ResourceManager.GetString("discountAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to discount code.
        /// </summary>
        internal static string discountCode {
            get {
                return ResourceManager.GetString("discountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register discount code.
        /// </summary>
        internal static string discountSet {
            get {
                return ResourceManager.GetString("discountSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hiest discount amount.
        /// </summary>
        internal static string disoucntMore {
            get {
                return ResourceManager.GetString("disoucntMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter.
        /// </summary>
        internal static string dofilter {
            get {
                return ResourceManager.GetString("dofilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download.
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download from cafe.
        /// </summary>
        internal static string downloadFromCafe {
            get {
                return ResourceManager.GetString("downloadFromCafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit personal info.
        /// </summary>
        internal static string editPersonalData {
            get {
                return ResourceManager.GetString("editPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mandetory.
        /// </summary>
        internal static string ejbari {
            get {
                return ResourceManager.GetString("ejbari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit Email.
        /// </summary>
        internal static string emailEdit {
            get {
                return ResourceManager.GetString("emailEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your email is registered successfully.
        /// </summary>
        internal static string emailRegistered {
            get {
                return ResourceManager.GetString("emailRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email is send for you friend successfully.
        /// </summary>
        internal static string emailSentVrif {
            get {
                return ResourceManager.GetString("emailSentVrif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finaliz order.
        /// </summary>
        internal static string endOrder {
            get {
                return ResourceManager.GetString("endOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sing up.
        /// </summary>
        internal static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string enter1 {
            get {
                return ResourceManager.GetString("enter1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string EnterPls {
            get {
                return ResourceManager.GetString("EnterPls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System error , contact with operator.
        /// </summary>
        internal static string erroCallOperator {
            get {
                return ResourceManager.GetString("erroCallOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report.
        /// </summary>
        internal static string errorReport {
            get {
                return ResourceManager.GetString("errorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error, try again.
        /// </summary>
        internal static string errorTryAgain {
            get {
                return ResourceManager.GetString("errorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review.
        /// </summary>
        internal static string examining {
            get {
                return ResourceManager.GetString("examining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit .
        /// </summary>
        internal static string exitAccount {
            get {
                return ResourceManager.GetString("exitAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit account.
        /// </summary>
        internal static string exitAccount1 {
            get {
                return ResourceManager.GetString("exitAccount1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to expressDelivery.
        /// </summary>
        internal static string expressDelivery {
            get {
                return ResourceManager.GetString("expressDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to family.
        /// </summary>
        internal static string family {
            get {
                return ResourceManager.GetString("family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to father name.
        /// </summary>
        internal static string fatherName {
            get {
                return ResourceManager.GetString("fatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to features.
        /// </summary>
        internal static string features {
            get {
                return ResourceManager.GetString("features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product filters.
        /// </summary>
        internal static string filterProduct {
            get {
                return ResourceManager.GetString("filterProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to final amount.
        /// </summary>
        internal static string finalPrice {
            get {
                return ResourceManager.GetString("finalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to follow us in social media.
        /// </summary>
        internal static string followUsInSocial {
            get {
                return ResourceManager.GetString("followUsInSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for email.
        /// </summary>
        internal static string forEmail {
            get {
                return ResourceManager.GetString("forEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forget password.
        /// </summary>
        internal static string forgetPassword {
            get {
                return ResourceManager.GetString("forgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for number.
        /// </summary>
        internal static string forNumber {
            get {
                return ResourceManager.GetString("forNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to click here.
        /// </summary>
        internal static string fromHereDownload {
            get {
                return ResourceManager.GetString("fromHereDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full list.
        /// </summary>
        internal static string fullList {
            get {
                return ResourceManager.GetString("fullList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallery.
        /// </summary>
        internal static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send code again.
        /// </summary>
        internal static string getCodeAgain {
            get {
                return ResourceManager.GetString("getCodeAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hashtags.
        /// </summary>
        internal static string hashtags {
            get {
                return ResourceManager.GetString("hashtags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string hezarToman {
            get {
                return ResourceManager.GetString("hezarToman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home.
        /// </summary>
        internal static string home1 {
            get {
                return ResourceManager.GetString("home1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in category.
        /// </summary>
        internal static string inCategory {
            get {
                return ResourceManager.GetString("inCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in date.
        /// </summary>
        internal static string inDate {
            get {
                return ResourceManager.GetString("inDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inplace payment.
        /// </summary>
        internal static string inPlacePayment {
            get {
                return ResourceManager.GetString("inPlacePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert correct email.
        /// </summary>
        internal static string inputRightEmail {
            get {
                return ResourceManager.GetString("inputRightEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your address.
        /// </summary>
        internal static string inputYourAddress {
            get {
                return ResourceManager.GetString("inputYourAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert city name.
        /// </summary>
        internal static string inputYourCity {
            get {
                return ResourceManager.GetString("inputYourCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your email.
        /// </summary>
        internal static string inputYourEmail {
            get {
                return ResourceManager.GetString("inputYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert you phone number.
        /// </summary>
        internal static string inputYourMobile {
            get {
                return ResourceManager.GetString("inputYourMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your name.
        /// </summary>
        internal static string inputYourName {
            get {
                return ResourceManager.GetString("inputYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your state.
        /// </summary>
        internal static string inputYourOstan {
            get {
                return ResourceManager.GetString("inputYourOstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert code.
        /// </summary>
        internal static string insertCode {
            get {
                return ResourceManager.GetString("insertCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert verification code.
        /// </summary>
        internal static string insertCodeVerif {
            get {
                return ResourceManager.GetString("insertCodeVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert discount code.
        /// </summary>
        internal static string insertDiscountCode {
            get {
                return ResourceManager.GetString("insertDiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your email.
        /// </summary>
        internal static string insertEmail {
            get {
                return ResourceManager.GetString("insertEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert you mobile number.
        /// </summary>
        internal static string insertMobilePhone {
            get {
                return ResourceManager.GetString("insertMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert new password.
        /// </summary>
        internal static string insertNewPass {
            get {
                return ResourceManager.GetString("insertNewPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert password.
        /// </summary>
        internal static string insertPassword {
            get {
                return ResourceManager.GetString("insertPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your password.
        /// </summary>
        internal static string insertPasswordd {
            get {
                return ResourceManager.GetString("insertPasswordd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert password again.
        /// </summary>
        internal static string insertRePassword {
            get {
                return ResourceManager.GetString("insertRePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your seleted name.
        /// </summary>
        internal static string insertSelectedName {
            get {
                return ResourceManager.GetString("insertSelectedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your password.
        /// </summary>
        internal static string insertYourPassword {
            get {
                return ResourceManager.GetString("insertYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill all fields please.
        /// </summary>
        internal static string insetAllData {
            get {
                return ResourceManager.GetString("insetAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert amount.
        /// </summary>
        internal static string insetPrice {
            get {
                return ResourceManager.GetString("insetPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instagram.
        /// </summary>
        internal static string instagram {
            get {
                return ResourceManager.GetString("instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payed.
        /// </summary>
        internal static string isPayed {
            get {
                return ResourceManager.GetString("isPayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product.
        /// </summary>
        internal static string kala {
            get {
                return ResourceManager.GetString("kala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product name.
        /// </summary>
        internal static string kalaName {
            get {
                return ResourceManager.GetString("kalaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purchase limit.
        /// </summary>
        internal static string limitkharid {
            get {
                return ResourceManager.GetString("limitkharid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you enterd successfully.
        /// </summary>
        internal static string logedInSuccessfully {
            get {
                return ResourceManager.GetString("logedInSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set valid email.
        /// </summary>
        internal static string loginEmailError {
            get {
                return ResourceManager.GetString("loginEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter to.
        /// </summary>
        internal static string loginTO {
            get {
                return ResourceManager.GetString("loginTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to make call.
        /// </summary>
        internal static string makeCall {
            get {
                return ResourceManager.GetString("makeCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3- in next level click on .
        /// </summary>
        internal static string marhale1 {
            get {
                return ResourceManager.GetString("marhale1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in top section.
        /// </summary>
        internal static string marhale2 {
            get {
                return ResourceManager.GetString("marhale2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mellat bank.
        /// </summary>
        internal static string mellat {
            get {
                return ResourceManager.GetString("mellat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2- select .
        /// </summary>
        internal static string menu1 {
            get {
                return ResourceManager.GetString("menu1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after swiping left opened menu.
        /// </summary>
        internal static string menu2 {
            get {
                return ResourceManager.GetString("menu2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your affiliate number.
        /// </summary>
        internal static string moarefMobile {
            get {
                return ResourceManager.GetString("moarefMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more.
        /// </summary>
        internal static string moreContent {
            get {
                return ResourceManager.GetString("moreContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My orders.
        /// </summary>
        internal static string myOrders {
            get {
                return ResourceManager.GetString("myOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my orders.
        /// </summary>
        internal static string myOrders1 {
            get {
                return ResourceManager.GetString("myOrders1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button in botton navbar.
        /// </summary>
        internal static string navar1 {
            get {
                return ResourceManager.GetString("navar1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1- click on.
        /// </summary>
        internal static string navar2 {
            get {
                return ResourceManager.GetString("navar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        internal static string newest {
            get {
                return ResourceManager.GetString("newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new password.
        /// </summary>
        internal static string newPassword {
            get {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert your new password.
        /// </summary>
        internal static string newPasswordAgain {
            get {
                return ResourceManager.GetString("newPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you new user?.
        /// </summary>
        internal static string newUser {
            get {
                return ResourceManager.GetString("newUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you new?.
        /// </summary>
        internal static string newUser1 {
            get {
                return ResourceManager.GetString("newUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no comment yet.
        /// </summary>
        internal static string noCommentYet {
            get {
                return ResourceManager.GetString("noCommentYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Product To List!.
        /// </summary>
        internal static string noItemAlert {
            get {
                return ResourceManager.GetString("noItemAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket has no item.
        /// </summary>
        internal static string noITemInBasket {
            get {
                return ResourceManager.GetString("noITemInBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no result found.
        /// </summary>
        internal static string noResult {
            get {
                return ResourceManager.GetString("noResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available.
        /// </summary>
        internal static string notAvailable {
            get {
                return ResourceManager.GetString("notAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not matter.
        /// </summary>
        internal static string notMatter {
            get {
                return ResourceManager.GetString("notMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit number.
        /// </summary>
        internal static string numberEdit {
            get {
                return ResourceManager.GetString("numberEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number is not registered.
        /// </summary>
        internal static string numberIsNotRg {
            get {
                return ResourceManager.GetString("numberIsNotRg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to only available.
        /// </summary>
        internal static string onlyAvailable {
            get {
                return ResourceManager.GetString("onlyAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to count of this item must not be greater than one.
        /// </summary>
        internal static string onlyOne {
            get {
                return ResourceManager.GetString("onlyOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order by.
        /// </summary>
        internal static string orderBy {
            get {
                return ResourceManager.GetString("orderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order date.
        /// </summary>
        internal static string orderDate {
            get {
                return ResourceManager.GetString("orderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order description.
        /// </summary>
        internal static string orderDetail {
            get {
                return ResourceManager.GetString("orderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order detail list.
        /// </summary>
        internal static string orderDetailList {
            get {
                return ResourceManager.GetString("orderDetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order list.
        /// </summary>
        internal static string orderFollow {
            get {
                return ResourceManager.GetString("orderFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to follow order.
        /// </summary>
        internal static string orderFollow1 {
            get {
                return ResourceManager.GetString("orderFollow1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order number.
        /// </summary>
        internal static string orderNumber {
            get {
                return ResourceManager.GetString("orderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order price.
        /// </summary>
        internal static string orderPrice {
            get {
                return ResourceManager.GetString("orderPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orders.
        /// </summary>
        internal static string orders {
            get {
                return ResourceManager.GetString("orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to original products.
        /// </summary>
        internal static string orginalProduct {
            get {
                return ResourceManager.GetString("orginalProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state.
        /// </summary>
        internal static string ostan {
            get {
                return ResourceManager.GetString("ostan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to other description.
        /// </summary>
        internal static string otherDesc {
            get {
                return ResourceManager.GetString("otherDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pasargad.
        /// </summary>
        internal static string pasargad {
            get {
                return ResourceManager.GetString("pasargad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password changed successfully.
        /// </summary>
        internal static string passChangeSuc {
            get {
                return ResourceManager.GetString("passChangeSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password charachter number must be greater than 7.
        /// </summary>
        internal static string passworChar {
            get {
                return ResourceManager.GetString("passworChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        internal static string pay {
            get {
                return ResourceManager.GetString("pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to different payment.
        /// </summary>
        internal static string payment {
            get {
                return ResourceManager.GetString("payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select your choice of payment.
        /// </summary>
        internal static string paymentChoice {
            get {
                return ResourceManager.GetString("paymentChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment status.
        /// </summary>
        internal static string paymentStat {
            get {
                return ResourceManager.GetString("paymentStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to waiting for payment.
        /// </summary>
        internal static string paymentWait {
            get {
                return ResourceManager.GetString("paymentWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to how to pay.
        /// </summary>
        internal static string paymentWay {
            get {
                return ResourceManager.GetString("paymentWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to personal information.
        /// </summary>
        internal static string personalData {
            get {
                return ResourceManager.GetString("personalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone number verification.
        /// </summary>
        internal static string phoneVerif {
            get {
                return ResourceManager.GetString("phoneVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert address details please.
        /// </summary>
        internal static string plsAddDetailAddress {
            get {
                return ResourceManager.GetString("plsAddDetailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to postal code.
        /// </summary>
        internal static string postalCode {
            get {
                return ResourceManager.GetString("postalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select your position.
        /// </summary>
        internal static string postionChoice {
            get {
                return ResourceManager.GetString("postionChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price ascending.
        /// </summary>
        internal static string priceASC {
            get {
                return ResourceManager.GetString("priceASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to price descending.
        /// </summary>
        internal static string priceDESC {
            get {
                return ResourceManager.GetString("priceDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to final amount.
        /// </summary>
        internal static string priceToPay {
            get {
                return ResourceManager.GetString("priceToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue to order.
        /// </summary>
        internal static string processContinue {
            get {
                return ResourceManager.GetString("processContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product color.
        /// </summary>
        internal static string proColor {
            get {
                return ResourceManager.GetString("proColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product features.
        /// </summary>
        internal static string productFeature {
            get {
                return ResourceManager.GetString("productFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product list.
        /// </summary>
        internal static string productList {
            get {
                return ResourceManager.GetString("productList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        internal static string profile1 {
            get {
                return ResourceManager.GetString("profile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately this product is not currently available. You can see similar products of this product through the list at the bottom of the page.
        /// </summary>
        internal static string proNAS {
            get {
                return ResourceManager.GetString("proNAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col.
        /// </summary>
        internal static string radif {
            get {
                return ResourceManager.GetString("radif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        internal static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        internal static string register1 {
            get {
                return ResourceManager.GetString("register1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register before?.
        /// </summary>
        internal static string registerBefor {
            get {
                return ResourceManager.GetString("registerBefor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to order registration date.
        /// </summary>
        internal static string registerDate {
            get {
                return ResourceManager.GetString("registerDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration in .
        /// </summary>
        internal static string registerIn {
            get {
                return ResourceManager.GetString("registerIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration in available only by email .
        /// </summary>
        internal static string registerOnlyEmail {
            get {
                return ResourceManager.GetString("registerOnlyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration in available only by phone number .
        /// </summary>
        internal static string registerOnlyMobile {
            get {
                return ResourceManager.GetString("registerOnlyMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remember me.
        /// </summary>
        internal static string rememberMe {
            get {
                return ResourceManager.GetString("rememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are you sure ?.
        /// </summary>
        internal static string removeConfirm {
            get {
                return ResourceManager.GetString("removeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repeat password.
        /// </summary>
        internal static string rePasswordnew {
            get {
                return ResourceManager.GetString("rePasswordnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password is not matched.
        /// </summary>
        internal static string repasswordWrong {
            get {
                return ResourceManager.GetString("repasswordWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sending message is successfull.
        /// </summary>
        internal static string resendCodeAgainSucc {
            get {
                return ResourceManager.GetString("resendCodeAgainSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return.
        /// </summary>
        internal static string returnButt {
            get {
                return ResourceManager.GetString("returnButt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character number must be greater than tree.
        /// </summary>
        internal static string searchLimit {
            get {
                return ResourceManager.GetString("searchLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to charachter number must be greater than three.
        /// </summary>
        internal static string searchLimit1 {
            get {
                return ResourceManager.GetString("searchLimit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search your product.
        /// </summary>
        internal static string searchSentence {
            get {
                return ResourceManager.GetString("searchSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search product , name , or categories you want.
        /// </summary>
        internal static string searchSentence1 {
            get {
                return ResourceManager.GetString("searchSentence1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search .
        /// </summary>
        internal static string searchWhatYouWant {
            get {
                return ResourceManager.GetString("searchWhatYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        internal static string seeAll {
            get {
                return ResourceManager.GetString("seeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seller answer in date .
        /// </summary>
        internal static string sellerAnswerAtDate {
            get {
                return ResourceManager.GetString("sellerAnswerAtDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seller in date.
        /// </summary>
        internal static string sellerInDate {
            get {
                return ResourceManager.GetString("sellerInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        internal static string send {
            get {
                return ResourceManager.GetString("send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verification code is sent.
        /// </summary>
        internal static string sentCode {
            get {
                return ResourceManager.GetString("sentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register first comment.
        /// </summary>
        internal static string setFirstComment {
            get {
                return ResourceManager.GetString("setFirstComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms and conditions.
        /// </summary>
        internal static string sharayetVghavanin {
            get {
                return ResourceManager.GetString("sharayetVghavanin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share by email.
        /// </summary>
        internal static string shareByEmail {
            get {
                return ResourceManager.GetString("shareByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show result for .
        /// </summary>
        internal static string showAllResultFor {
            get {
                return ResourceManager.GetString("showAllResultFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to similar product.
        /// </summary>
        internal static string similarProp {
            get {
                return ResourceManager.GetString("similarProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Products.
        /// </summary>
        internal static string specialKind {
            get {
                return ResourceManager.GetString("specialKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Offer.
        /// </summary>
        internal static string specialOffer {
            get {
                return ResourceManager.GetString("specialOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to payment status.
        /// </summary>
        internal static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your order is registerd successfully.
        /// </summary>
        internal static string successOrderRegistraion {
            get {
                return ResourceManager.GetString("successOrderRegistraion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support.
        /// </summary>
        internal static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to system error.
        /// </summary>
        internal static string systemError {
            get {
                return ResourceManager.GetString("systemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to agreement.
        /// </summary>
        internal static string tavafoghi {
            get {
                return ResourceManager.GetString("tavafoghi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are available 24 hours a day, seven days a week.
        /// </summary>
        internal static string teamAvailable {
            get {
                return ResourceManager.GetString("teamAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone .
        /// </summary>
        internal static string telephone {
            get {
                return ResourceManager.GetString("telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms and conditions.
        /// </summary>
        internal static string terms {
            get {
                return ResourceManager.GetString("terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use terms.
        /// </summary>
        internal static string termsOfServic {
            get {
                return ResourceManager.GetString("termsOfServic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $.
        /// </summary>
        internal static string toman {
            get {
                return ResourceManager.GetString("toman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total price.
        /// </summary>
        internal static string totalPrice {
            get {
                return ResourceManager.GetString("totalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total sum.
        /// </summary>
        internal static string totalSum {
            get {
                return ResourceManager.GetString("totalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add to your home screen.
        /// </summary>
        internal static string toYourPage {
            get {
                return ResourceManager.GetString("toYourPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not available.
        /// </summary>
        internal static string unAvailable {
            get {
                return ResourceManager.GetString("unAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to understand.
        /// </summary>
        internal static string understand {
            get {
                return ResourceManager.GetString("understand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user address.
        /// </summary>
        internal static string userAddress {
            get {
                return ResourceManager.GetString("userAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users comments.
        /// </summary>
        internal static string userComment {
            get {
                return ResourceManager.GetString("userComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to users comments about.
        /// </summary>
        internal static string userCommentAbout {
            get {
                return ResourceManager.GetString("userCommentAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user phone number .
        /// </summary>
        internal static string userPhoneNumber {
            get {
                return ResourceManager.GetString("userPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view more.
        /// </summary>
        internal static string viewItem {
            get {
                return ResourceManager.GetString("viewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view product.
        /// </summary>
        internal static string viewProduct {
            get {
                return ResourceManager.GetString("viewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wallet.
        /// </summary>
        internal static string wallet {
            get {
                return ResourceManager.GetString("wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using wallet.
        /// </summary>
        internal static string walletUse {
            get {
                return ResourceManager.GetString("walletUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom amount (less than 100 thousand tomans).
        /// </summary>
        internal static string wantedPrice {
            get {
                return ResourceManager.GetString("wantedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show all.
        /// </summary>
        internal static string watchAll {
            get {
                return ResourceManager.GetString("watchAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view and purchase .
        /// </summary>
        internal static string watchAndPurchase {
            get {
                return ResourceManager.GetString("watchAndPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web application.
        /// </summary>
        internal static string webapplication {
            get {
                return ResourceManager.GetString("webapplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcome.
        /// </summary>
        internal static string welcom {
            get {
                return ResourceManager.GetString("welcom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we will be in touch.
        /// </summary>
        internal static string willBeInTouch {
            get {
                return ResourceManager.GetString("willBeInTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorites.
        /// </summary>
        internal static string wishItem {
            get {
                return ResourceManager.GetString("wishItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert content.
        /// </summary>
        internal static string writeContetnComment {
            get {
                return ResourceManager.GetString("writeContetnComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert comment.
        /// </summary>
        internal static string writeYourComment {
            get {
                return ResourceManager.GetString("writeYourComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong captcha.
        /// </summary>
        internal static string wrongCaptcha {
            get {
                return ResourceManager.GetString("wrongCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verification code is not valid.
        /// </summary>
        internal static string wrongCode {
            get {
                return ResourceManager.GetString("wrongCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are our proirity.
        /// </summary>
        internal static string youAreInProirity {
            get {
                return ResourceManager.GetString("youAreInProirity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you can comment about this product.
        /// </summary>
        internal static string youCanComment {
            get {
                return ResourceManager.GetString("youCanComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        internal static string yourAccount {
            get {
                return ResourceManager.GetString("yourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have already purchased this product, by logging in to your account, your opinion will be registered as the owner of the product..
        /// </summary>
        internal static string yourCommentStat {
            get {
                return ResourceManager.GetString("yourCommentStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comment title.
        /// </summary>
        internal static string yourCommentTitle {
            get {
                return ResourceManager.GetString("yourCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you profit.
        /// </summary>
        internal static string yourProfit {
            get {
                return ResourceManager.GetString("yourProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zarinpal.
        /// </summary>
        internal static string zarin {
            get {
                return ResourceManager.GetString("zarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24 hour support.
        /// </summary>
        internal static string _724 {
            get {
                return ResourceManager.GetString("724", resourceCulture);
            }
        }
    }
}
